Repository codedex-io/projects, pull requests merged in 2022-10, with the labels that each got.

#10 Add new tutorial: Web Scrape Amazon with Beautiful Soup
  projects/web-scrape-amazon-with-beautiful-soup/amazon-product-page.png
  projects/web-scrape-amazon-with-beautiful-soup/demo.gif
  projects/web-scrape-amazon-with-beautiful-soup/extracting-price.png
  projects/web-scrape-amazon-with-beautiful-soup/extracting-title.png
  projects/web-scrape-amazon-with-beautiful-soup/header.png
  projects/web-scrape-amazon-with-beautiful-soup/inspect-element.gif
  projects/web-scrape-amazon-with-beautiful-soup/request-headers.png
  projects/web-scrape-amazon-with-beautiful-soup/scraper.py
  projects/web-scrape-amazon-with-beautiful-soup/web-scrape-amazon-with-beautiful-soup.mdx
Labels: python, new project

#12 changed double quotes to single quotes
  projects/visualize-youtube-data-with-plotly/visualize-youtube-data-with-plotly.mdx
Labels: enhancement

#23 Fix Typo
  .github/CONTRIBUTING.md
Labels: typo
